import type { DynamicValidationResult, FrameworkDecision, Locale } from "@/src/validation/types";

export type ValidationReportDocument = {
  filename: string;
  generatedAt: string;
  text: string;
};

type ValidationReportInput = {
  idea: string;
  email?: string;
  locale: Locale;
  result: DynamicValidationResult;
};

function decisionLabel(decision: FrameworkDecision): string {
  if (decision === "CONDITIONAL_GO") return "CONDITIONAL GO";
  if (decision === "NEED_WORK") return "NEEDS WORK";
  if (decision === "NO_GO") return "NO GO";
  return "GO";
}

function safeSegment(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 42);
}

function toIntegerScore(value: number): number {
  return Math.round(Math.max(0, Math.min(100, value * 20)));
}

function resolveReportScore(result: DynamicValidationResult): number {
  if (typeof result.frameworkReport?.weightedScore === "number") {
    return Math.max(0, Math.min(100, Math.round(result.frameworkReport.weightedScore)));
  }
  return toIntegerScore(result.overallScore);
}

function linesWithFallback(title: string, lines: string[]): string[] {
  if (lines.length === 0) return [title, "- n/a"];
  return [title, ...lines.map((line) => `- ${line}`)];
}

export function buildValidationReportDocument(input: ValidationReportInput): ValidationReportDocument {
  const generatedAt = new Date().toISOString();
  const shortIdea = input.idea.split(/\s+/).slice(0, 6).join("-");
  const filename = `bizsproutai-validation-${safeSegment(shortIdea || "report")}.txt`;

  const frameworkDecision = input.result.frameworkReport?.decision;
  const decision = frameworkDecision
    ? decisionLabel(frameworkDecision)
    : input.result.status === "GO"
      ? "GO"
      : input.result.status === "STOP"
        ? "NO GO"
        : "NEEDS WORK";

  const demand = input.result.frameworkReport?.problemDemand.total;
  const competition = input.result.frameworkReport?.solutionValidation.differentiation;
  const modelMargin = input.result.frameworkReport?.businessModelValidation.margin;
  const gates = input.result.frameworkReport?.gates ?? [];
  const reportScore = resolveReportScore(input.result);

  const reportLines: string[] = [
    "BizSproutAI Validation Report",
    "============================",
    "Brand: BizSproutAI (logo is embedded in the PDF report version)",
    `Generated: ${generatedAt}`,
    `Locale: ${input.locale}`,
    `Email: ${input.email ?? "not provided"}`,
    "",
    "Submitted Idea",
    "--------------",
    input.idea,
    "",
    "Decision",
    "--------",
    `${decision} (${reportScore}/100)`,
    "",
    "Context",
    "-------",
    `Category: ${input.result.category}`,
    `Country: ${input.result.country.code}`,
    `Framework: ${input.result.framework?.label ?? "General"}`,
    "",
    "One-Line Summary",
    "----------------",
    input.result.summary.oneLiner,
    "",
    "Simple Breakdown",
    "----------------",
    `Demand: ${typeof demand === "number" ? `${demand}/20` : "n/a"}`,
    `Competition: ${typeof competition === "number" ? `${competition}/5` : "n/a"}`,
    `Business Model Margin: ${typeof modelMargin === "number" ? `${modelMargin}%` : "n/a"}`,
    "",
    ...linesWithFallback("Top Opportunities", input.result.summary.topOpportunities),
    "",
    ...linesWithFallback("Biggest Risks", input.result.summary.biggestRisks),
    "",
    ...linesWithFallback("Next Actions (30-Day Launch Sprint Preview)", input.result.nextActions.slice(0, 10)),
    "",
    "Gate Analysis",
    "-------------",
    ...(gates.length
      ? gates.map(
          (gate) => {
            if (gate.status === "BLOCKED") {
              return `- Gate ${gate.gate} ${gate.name}: BLOCKED (waiting for Gate ${gate.blockedByGate})`;
            }
            return `- Gate ${gate.gate} ${gate.name}: ${gate.status} (${gate.score}/${gate.maxScore})`;
          }
        )
      : ["- n/a"]),
    "",
    "Generated by BizSproutAI",
  ];

  return {
    filename,
    generatedAt,
    text: reportLines.join("\n"),
  };
}
